version: "3"

services: 
  db:
    image: postgres
    restart: always
    ports: 
      - 5432:5432 
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=exmeal_dev
    volumes: 
      - pgdata:/data/postgres

  test_db:
    image: postgres
    restart: always
    ports: 
      - 5432:5432 
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=exmeal_test
    volumes: 
      - pgdata:/data/postgres

volumes: 
  pgdata: 
    driver: local